Newhoggy/rename cardano.cli.run.era based
IntersectMBO/cardano-cli pull request #119
Opened 2023-07-30 12:15 UTC by newhoggy

# Changelog

```yaml
- description: |
    Refactoring:
    - Rename Cardano.CLI.Commands.EraBased module Cardano.CLI.EraBased.Commands
    - Merge ShelleyGovernanceCmdError into GovernanceCmdError and renderShelleyGovernanceError into renderGovernanceError
    - Merge Cardano.CLI.Run.Legacy.Governance module into Cardano.CLI.EraBased.Run.Governance
    - Rename runGovernanceDelegrationCertificate to runGovernanceDelegationCertificate
    - Rename Cardano.CLI.EraBased.Certificate module to Cardano.CLI.EraBased.Run.Certificate
    - Rename Cardano.CLI.Run.EraBased to Cardano.CLI.EraBased.Run  # no-changes: the API has not changed
  compatibility: breaking
  type: maintenance
```

# Context

Addititional context for the PR goes here.

If the PR fixes a particular issue please provide a
[link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=)
to the issue.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] The change log section in the PR description has been filled in
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - roundtrip tests
  - integration tests
  See [Runnings tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] The changelog section in the PR is updated to describe the change
- [ ] Self-reviewed the diff

# Note on CI
If your PR is from a fork, the necessary CI jobs won't trigger automatically for security reasons.
You will need to get someone with write privileges.  Please contact IOG node developers to do this
for you.

2023-07-31 10:57 UTC, carbolymer commented on cardano-cli/src/Cardano/CLI/Commands/Governance.hs
> +renderGovernanceError :: GovernanceCmdError -> Text
That's already implemented as a part of https://github.com/input-output-hk/cardano-cli/pull/84/files

2023-07-31 14:15 UTC, Jimbo4350 requested changes
Let's merge #110 and #114 first.

2023-08-04 16:23 UTC, newhoggy commented on cardano-cli/src/Cardano/CLI/Commands/Governance.hs
> +renderGovernanceError :: GovernanceCmdError -> Text
Deleted

2023-08-04 16:54 UTC, Jimbo4350 approved these changes

2023-08-05 08:27 UTC, merged