View vote file
IntersectMBO/cardano-cli pull request #303
Opened 2023-09-22 12:12 UTC by carlhammann

# Changelog

```yaml
- description: |
    Added a command to inspect a vote file: `cardano-cli conway governance vote view`
# uncomment types applicable to the change:
  type:
  - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

This PR closes #11.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [x] The change log section in the PR description has been filled in
- [x] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - round trip tests
  - integration tests
  See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] The version bounds in `.cabal` files are updated
- [x] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] The changelog section in the PR is updated to describe the change
- [x] Self-reviewed the diff

2023-09-24 01:48 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/governance/vote/voteView
> +    decision: VoteYes
We should output `JSON` by default.  I like the idea of supporting `YAML` as an option.

2023-09-24 01:49 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/governance/vote/voteView
> +    decision: VoteYes
Should we drop the `anchor` field if its value is missing?

2023-09-24 01:51 UTC, newhoggy commented
In the Change log section of the PR description, mark `compatible` because you have a change to the CLI parser, but it adds a new command which is a non-breaking change.

2023-09-25 10:54 UTC, carlhammann commented on cardano-cli/test/cardano-cli-golden/files/golden/governance/vote/voteView
> +    decision: VoteYes
> We should output `JSON` by default. I like the idea of supporting `YAML` as an option.

Got it. I was taking inspiration from the `cardano-cli * transaction view` commands, which output `YAML` as well.

> Should we drop the `anchor` field if its value is missing?

I'm not sure. My "role model" `transaction view` commands don't. Dropping the field _might_ make parsing the output back into types of suitable shapes harder for third parties.

2023-09-26 12:06 UTC, carlhammann commented on cardano-cli/test/cardano-cli-golden/files/golden/governance/vote/voteView
> +    decision: VoteYes
@newhoggy I've now added a `--yaml` option to switch to YAML output. Without that, the output is JSON. 

As this is my first PR here: how do we proceed to merging this? I'm unsure about the "commit sequence broadly makes sense" requirement -- what are your customs there? (I'd say the PR is simple enough to get squashed.)

2023-09-26 12:33 UTC, Jimbo4350 requested changes, later dismissed
Nice, some changes needed.

2023-09-26 12:33 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/EraBased/Options/Governance/Vote.hs
> +    ( Opt.progDesc "Vote commands." )
spaces after and before parentheses

2023-09-26 12:33 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/EraBased/Options/Governance/Vote.hs
> +        ( GovernanceVoteViewCmd <$> pAnyVoteViewCmd w)
space after first `(`

2023-09-26 12:33 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/EraBased/Options/Governance/Vote.hs
> +    pYamlOutput :: Parser Bool
Why YAML? Let's stick with JSON as this is the usual output we use in the cli.

2023-09-26 12:33 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Vote.hs
> +  Bool
should be: 
```
runGovernanceVoteViewCmd 
  :: Bool
```

Have you seen the style guide? https://github.com/input-output-hk/cardano-node-wiki/wiki/Style-guide

2023-09-26 12:33 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Vote.hs
> +  let sbe = conwayEraOnwardsToShelleyBasedEra w in
We usually do a line break after the `let` definition

2023-09-26 12:33 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Vote.hs
> +      then BS.putStr . Yaml.encodePretty (Yaml.setConfCompare compare Yaml.defConfig)
We should have an option to write to disk (`--out-file`) or output to stdout

2023-09-26 12:33 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/EraBased/Commands/Governance/Vote.hs
> +      (AnyVoteViewCmd era)
So this can be simplified to `VoteFile In` because the parser decides for us if this command is allowed or not in a given era.

2023-09-26 12:33 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Read.hs
> +    VotesNotSupportedInEra era ->
We should not need `VotesNotSupportedInEra`.

2023-09-26 12:43 UTC, carlhammann commented on cardano-cli/src/Cardano/CLI/EraBased/Options/Governance/Vote.hs
> +    pYamlOutput :: Parser Bool
I was taking inspiration from the `cardano-cli * transaction view` command, which, AFAICT, also outputs YAML. See this discussion: https://github.com/input-output-hk/cardano-cli/pull/303#discussion_r1335088169
I'm fine with removing the option, though.

2023-09-26 12:44 UTC, carlhammann commented on cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Vote.hs
> +  Bool
I have, and now I've also discovered that I've misconfigured my vim... Thanks! :bow:

2023-09-26 12:55 UTC, carlhammann commented on cardano-cli/src/Cardano/CLI/EraBased/Commands/Governance/Vote.hs
> +      (AnyVoteViewCmd era)
I thought so too, at first, but then where do I get my witness for the [actual implementation](https://github.com/input-output-hk/cardano-cli/blob/d7967b08e76efe1786cd4f55c25e1dce0b020aeb/cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Vote.hs#L90C1-L90C1) of the command? I want to use [`readVotingProceduresFile`](https://github.com/input-output-hk/cardano-cli/blob/23b02a2be233dfdf5a8064c295f0275135d2094c/cardano-cli/src/Cardano/CLI/Read.hs#L773), and that means I need something of type `ConwayOnwardsEra era`. Can I get that some other way? (I agree that that would be cleaner.)

(Then, there's also the YAML thing, but I see that, if we remove that, we're really back to only a file handle.)

2023-09-26 16:11 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/EraBased/Commands/Governance/Vote.hs
> +      (AnyVoteViewCmd era)
Apologies, you're right you do need `ConwayEraOnwards era`

2023-09-27 14:57 UTC, carlhammann commented
I think this is ready, barring the YAML issue. @Jimbo4350 did I understand you correctly yesterday that we'll keep the YAML option, and adapt the other commands that currently output _only_ YAML to also output JSON by default, with a switch like the one on this command?

2023-10-04 13:28 UTC, newhoggy commented
I rebased and updated for `cardano-api-8.25.0.1`.

2023-10-04 13:28 UTC, newhoggy approved these changes

2023-10-09 10:01 UTC, merged