Fix missing redeemers in certificate delegation and deregistration
IntersectMBO/cardano-cli pull request #306
Opened 2023-09-25 09:04 UTC by carbolymer

# Changelog

```yaml
- description: |
    <insert-changelog-description-here>
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here.

If the PR fixes a particular issue please provide a
[link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=)
to the issue.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] The change log section in the PR description has been filled in
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - round trip tests
  - integration tests
  See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] The changelog section in the PR is updated to describe the change
- [ ] Self-reviewed the diff

2023-09-29 19:12 UTC, carbolymer commented
This PR is not building, because it requires patterns exports available in cardano-api-8.23, which is introduced in: https://github.com/input-output-hk/cardano-cli/pull/320

2023-10-02 12:57 UTC, Jimbo4350 requested changes

2023-10-02 12:57 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Types/Errors/TxValidationError.hs
> -{-# OPTIONS_GHC -Wno-incomplete-uni-patterns #-}
:+1:

2023-10-02 12:57 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Types/Errors/TxValidationError.hs
> +        case shelleyCert of
Don't we have this function in `cardano-api`?

2023-10-03 09:12 UTC, carbolymer commented on cardano-cli/src/Cardano/CLI/Types/Errors/TxValidationError.hs
> +        case shelleyCert of
These are similar ones, but are not the same: https://github.com/input-output-hk/cardano-api/blob/151eff181cb1782f9db46dbea36d22e8d40f0545/cardano-api/internal/Cardano/Api/Certificate.hs#L670

Should we extract stake creds only for deregistration and delegation like the comment says here, or should we use stake credential witness for the cases when it's available?

2023-10-03 13:37 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Types/Errors/TxValidationError.hs
> +        case shelleyCert of
We can leave it as it for now. We should follow the specification and document it here

2023-10-03 13:37 UTC, Jimbo4350 approved these changes

2023-10-04 13:36 UTC, merged