Update to cardano-api 8.24
IntersectMBO/cardano-cli pull request #320
Opened 2023-09-29 18:24 UTC by carbolymer

# Changelog

```yaml
- description: |
    Update to cardano-api 8.24
# uncomment types applicable to the change:
  type:
   - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
   - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Requires:
- https://github.com/input-output-hk/cardano-api/pull/287
for additional ledger reexports and `AnyEraInEon` changes.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] The change log section in the PR description has been filled in
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - round trip tests
  - integration tests
  See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] The changelog section in the PR is updated to describe the change
- [ ] Self-reviewed the diff

2023-09-29 18:44 UTC, carbolymer commented on cardano-cli/cardano-cli.cabal
> -                      , cardano-api ^>= 8.22
TODO:
- [ ] use 8.24 after release
- [ ] bump flake.lock
- [ ] bump chap index in cabal.project

2023-09-29 18:44 UTC, carbolymer commented on cardano-cli/src/Cardano/CLI/EraBased/Options/Governance/Actions.hs
> +ppDRepActivity = pure SNothing -- TODO Conway
TODO Parsers are stubbed to make changes smaller. To be implemented in the next PR.

2023-09-29 18:45 UTC, carbolymer commented
Build fails because it requires unreleased cardano-api changes. To be fixed prior to merge.

2023-10-02 12:44 UTC, Jimbo4350 requested changes, later dismissed
I'm not sold on `AnyEraInEon`

2023-10-02 13:32 UTC, newhoggy commented
As agreed, `AnyEraInEon` will be renamed to `EraInEon` in a future PR.

2023-10-02 13:32 UTC, newhoggy approved these changes

2023-10-02 13:42 UTC, Jimbo4350 approved these changes

2023-10-02 13:53 UTC, merged