#213 Add check for keys permissions in the test in governance drep key-gen
IntersectMBO/cardano-cli pull request #401
Opened 2023-10-24 17:35 UTC by carbolymer

# Changelog

```yaml
- description: |
    Add check for keys permissions in the test in governance drep key-gen
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
   - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Closes #213 

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

2023-10-25 13:22 UTC, carlhammann requested changes

2023-10-25 13:22 UTC, carlhammann commented on cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/DRep.hs
> +    sgnMode <- retrievePermissions verificationKeyFile
```suggestion
    sgnMode <- retrievePermissions signingKeyFile
```

2023-10-25 13:58 UTC, Jimbo4350 approved these changes
LGTM but have a look at Carl's comment.

2023-10-26 10:48 UTC, carbolymer commented on cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/DRep.hs
> +    sgnMode <- retrievePermissions verificationKeyFile
Good catch, thanks!

2023-10-26 10:54 UTC, carlhammann approved these changes

2023-10-26 11:24 UTC, merged