Remove keys coercing
IntersectMBO/cardano-cli pull request #412
Opened 2023-10-30 17:29 UTC by carbolymer

# Changelog

```yaml
- description: |
    Remove keys coercing
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
   - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
   - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here. If the PR fixes a particular issue please provide a [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) to the issue.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2023-10-30 17:47 UTC, CarlosLopezDeLara approved these changes

2023-10-31 13:11 UTC, Jimbo4350 requested changes
The proposal type is as follows:

```
data ProposalProcedure era = ProposalProcedure
  { pProcDeposit :: !Coin
  , pProcReturnAddr :: !(RewardAcnt (EraCrypto era))
  , pProcGovAction :: !(GovAction era)
  , pProcAnchor :: !(Anchor (EraCrypto era))
  }
```
Both key and script based address should be able to receive the deposit.

2023-10-31 13:11 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Actions.hs
> +  withdrawals <- forM treasuryWithdrawal $ \(verificationKeyOrHashOrFile, lovelace) -> do
Why this change? Treasury withdrawals should work with scripts as well:
```
...
  | TreasuryWithdrawals
      -- | Proposed treasury withdrawals
      !(Map (RewardAcnt (EraCrypto era)) Coin)
...

data RewardAcnt c = RewardAcnt
  { getRwdNetwork :: !Network
  , getRwdCred :: !(Credential 'Staking c)
  }

```

2023-10-31 13:16 UTC, Jimbo4350 approved these changes

2023-11-03 11:10 UTC, closed without merging

2023-11-03 11:10 UTC, carbolymer commented
Superceded by: https://github.com/input-output-hk/cardano-cli/pull/430