Introduce handshake command + tighter ping UI
IntersectMBO/cardano-cli pull request #468
Opened 2023-11-21 12:59 UTC by smelc

# Changelog

```yaml
- description: |
    TBD
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Fixes https://github.com/input-output-hk/cardano-cli/issues/49

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2023-11-22 15:06 UTC, Jimbo4350 requested changes

2023-11-22 15:06 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Run/HandShake.hs
> +  { endPoint        :: !Ping.EndPoint
This shouldn't be a separate command. It should live under the ping command as something like `handshake-only`.

2023-11-23 16:36 UTC, carbolymer commented on cardano-cli/src/Cardano/CLI/Run/HandShake.hs
handshake is a single word, so the module should be named `Handshake`

2023-11-23 16:36 UTC, carbolymer commented on cardano-cli/src/Cardano/CLI/Run/HandShake.hs
> +module Cardano.CLI.Run.HandShake
Handshake is a single word, so the module should be named `Handshake`

```suggestion
module Cardano.CLI.Run.Handshake
```

2023-12-13 14:25 UTC, smelc commented on cardano-cli/src/Cardano/CLI/Run/HandShake.hs
> +  { endPoint        :: !Ping.EndPoint
We've settled for `cardano-cli ping --handshake-only`  [here on Slack](https://input-output-rnd.slack.com/archives/C031GFLC3DF/p1701360655094909?thread_ts=1701253501.603859&cid=C031GFLC3DF).

2024-01-02 10:36 UTC, smelc commented
Will likely be superseded by #524 in the end

2024-03-15 09:27 UTC, closed without merging