initial draft of create-hardfork cmd
IntersectMBO/cardano-cli pull request #746
Opened 2024-05-01 18:55 UTC by CarlosLopezDeLara

# Changelog

```yaml
- description: |
    Introduces the `governance action create-hardfork` cmd.   
# uncomment types applicable to the change:
  type:
  - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Closes https://github.com/IntersectMBO/cardano-cli/issues/721
 
# How to trust this PR

Run the command 
```
cardano-cli conway governance action create-hardfork --testnet \
--governance-action-deposit 50000000000 \
--deposit-return-stake-verification-key-file keys/stake.vkey \
--anchor-url https://github.com/carloslodelar/proposals/blob/main/why-hardfork-to-10.txt \
-anchor-data-hash c03fbc37eaea33969475fd1b2a004c88250a4a18a40b099d151a91d2e1b4fb6e \
--protocol-major-version 10 \
--protocol-minor-version 0 \
--out-file transactions/hardforkinit.action
```
Explore the text envelope en check it with cbor.me 
{
    "type": "Governance proposal",
    "description": "",
    "cborHex": "841b0000000ba43b7400581de008f121b36abf2bcdd7daa2551c1e6653413a78c419e170d3319924d38301f6820a0082784b68747470733a2f2f6769746875622e636f6d2f6361726c6f736c6f64656c61722f70726f706f73616c732f626c6f622f6d61696e2f7768792d68617264666f726b2d746f2d31302e7478745820c03fbc37eaea33969475fd1b2a004c88250a4a18a40b099d151a91d2e1b4fb6e"
}

or with 
```
cardano-cli conway governance action view --action-file transactions/hardforkinit.action 
{
    "anchor": {
        "dataHash": "c03fbc37eaea33969475fd1b2a004c88250a4a18a40b099d151a91d2e1b4fb6e",
        "url": "https://github.com/carloslodelar/proposals/blob/main/why-hardfork-to-10.txt"
    },
    "deposit": 50000000000,
    "governance action": {
        "contents": [
            null,
            {
                "major": 10,
                "minor": 0
            }
        ],
        "tag": "HardForkInitiation"
    },
    "return address": {
        "credential": {
            "keyHash": "08f121b36abf2bcdd7daa2551c1e6653413a78c419e170d3319924d3"
        },
        "network": "Testnet"
    }
}
```
# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

2024-05-02 08:28 UTC, carbolymer approved these changes
LGTM, nice job! Can you add a test for that, similarly to the other ones here: https://github.com/IntersectMBO/cardano-cli/blob/main/cardano-cli/test/cardano-cli-golden/Test/Golden/Governance/Action.hs

2024-05-02 08:32 UTC, carbolymer commented
The windows CI failure: https://github.com/IntersectMBO/cardano-node/pull/5811#issuecomment-2089561098

2024-05-02 09:22 UTC, smelc requested changes
LGTM :champagne: A few typos in the help needs fixing.

2024-05-02 09:22 UTC, smelc commented on cardano-cli/src/Cardano/CLI/EraBased/Options/Governance/Actions.hs
> +    $ Opt.progDesc "Create a hardfork inititation proposal."
```suggestion
    $ Opt.progDesc "Create a hardfork initiation proposal."
```

2024-05-02 09:22 UTC, smelc commented on cardano-cli/src/Cardano/CLI/EraBased/Options/Governance/Actions.hs
> +              <*> pFileOutDirection "out-file" "Output filepath of the no confidence proposal."
```suggestion
              <*> pFileOutDirection "out-file" "Output filepath of the create hardfork proposal."
```

2024-05-02 09:22 UTC, smelc commented on cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Actions.hs
> +      , Cmd.proposalHash
```suggestion
      , Cmd.proposalHash = anchorDataHash
```

goes with the punning below

2024-05-02 09:22 UTC, smelc commented on cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Actions.hs
> +        , L.anchorDataHash = proposalHash
```suggestion
        , L.anchorDataHash
```

2024-05-02 09:22 UTC, smelc commented on cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Actions.hs
> +    $ writeFileTextEnvelope outFile Nothing proposalProcedure
Could we replace the `Nothing` by something, so that the generated proposal has an helpful description text?

2024-05-02 11:13 UTC, Jimbo4350 reviewed
LGTM! Feel free to merge after @smelc approves.

2024-05-02 18:45 UTC, CarlosLopezDeLara commented on cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Actions.hs
> +    $ writeFileTextEnvelope outFile Nothing proposalProcedure
addressed in latest commit

Would be good to do the same on all other action files.

2024-05-03 10:00 UTC, smelc approved these changes

2024-05-03 13:38 UTC, Jimbo4350 requested changes
The commit history needs to be cleaned up. Squashing commits and leaving a commit message like: 
```
[Squashed commit of the following:](https://github.com/IntersectMBO/cardano-cli/pull/746/commits/9bc83f86e37c5613c6e6e589c1605d7b95817d6e)

commit https://github.com/IntersectMBO/cardano-cli/commit/82cc5c1ab7ff50d4072a4e4dea0ba9f6665e04be
Merge: https://github.com/IntersectMBO/cardano-cli/commit/8229fc0c0e3d07f26f1c0707893cf5544746e115 https://github.com/IntersectMBO/cardano-cli/commit/e3dc0a02ffdcd44779a7a7dac99d68d1cc235bdc
Author: Carlos LopezDeLara <carlos.lopezdelara@iohk.io>
Date:   Thu May 2 13:10:52 2024 -0600

    Merge branch 'cl/hardforkinit' of github.com:IntersectMBO/cardano-cli into cl/hardforkinit

commit https://github.com/IntersectMBO/cardano-cli/commit/8229fc0c0e3d07f26f1c0707893cf5544746e115
Author: Carlos LopezDeLara <carlos.lopezdelara@iohk.io>
Date:   Wed May 1 12:09:49 2024 -0600

    action create-hardfork command

    Co-Authored-By: Clément Hurlin <smelc@users.noreply.github.com>

commit https://github.com/IntersectMBO/cardano-cli/commit/e3dc0a02ffdcd44779a7a7dac99d68d1cc235bdc
Author: Carlos LopezDeLara <carlos.lopezdelara@iohk.io>
Date:   Wed May 1 12:09:49 2024 -0600

    action create-hardfork command

    Co-Authored-By: Clément Hurlin <smelc@users.noreply.github.com>

@CarlosLopezDeLara
```
Is not very readable. When you squash commits you summarize the changes in those commits in a concise and clear manner. 

I also don't know what is happening in `3d8a21f4792c0983b94f493ee064a3203a1c86da`.

2024-05-03 13:48 UTC, smelc commented
@CarlosLopezDeLara> those commits should not be here: 

![image](https://github.com/IntersectMBO/cardano-cli/assets/634720/3316a646-2cf8-4b40-bfb9-7ae660ac905c)

Since they have been merged already. I can help you clean this up during our pair programming session :+1:

2024-05-03 14:04 UTC, Jimbo4350 approved these changes
LGTM!

2024-05-03 14:19 UTC, merged