Depend on optparse-applicative instead of optparse-applicative-fork
IntersectMBO/cardano-cli pull request #899
Opened 2024-09-18 09:59 UTC by smelc

# Changelog

```yaml
- description: |
    Depend on optparse-applicative instead of optparse-applicative-fork
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  - refactoring    # QoL changes
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

We want to get rid on our dependency to [optparse-applicative-fork](https://github.com/input-output-hk/optparse-applicative) here: https://github.com/IntersectMBO/cardano-cli/blob/ca494098df110dfcc23f14ef6635ec1b062baddf/cardano-cli/cardano-cli.cabal#L245.

This PR does this, as well as showing what it happens if we take a vanilla version of `optparse-applicative`. This is what the commit `Changes to golden files WITHOUT change to optparse-applicative` shows.

Then the last commit, named `Changes to golden files WITH change to optparse-applicative` shows what we can achieve if we [tweak `optparse-applicative` slightly](https://github.com/smelc/optparse-applicative/commits/smelc/wip-cardano-cli-usecase/). In this case the changes to golden files is minimal (pipes move to the left, and then are more single line disjunctions, but they are fine IMHO).

# How to trust this PR

Look at the golden files. See that the end state is quite nice.

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- [X] Self-reviewed the diff

2024-09-18 10:02 UTC, smelc commented on cardano-cli/src/Cardano/CLI/Options.hs
> +      -- , helpEmbedBriefDesc PP.align
This is the magical configuration bit that makes the golden files still look good. The changes in https://github.com/smelc/optparse-applicative/commits/smelc/wip-cardano-cli-usecase/ are hardcoding this configuration change for now, but my plan is to make a PR to `optparse-applicative` to make this configurable.

2025-03-18 10:19 UTC, smelc commented
Because `optparse-applicative` [should be released soon](https://github.com/pcapriotti/optparse-applicative/pull/494#issuecomment-2731879472), we should be able to merge this PR soonish.

That is why I'm assigning it to you @nbacquey :slightly_smiling_face:

2025-04-03 12:19 UTC, smelc commented
This will be mergeable soon: https://github.com/pcapriotti/optparse-applicative/pull/494#issuecomment-2773906969

cc @carbolymer @nbacquey

2025-06-03 13:02 UTC, smelc commented
Seems this can be finished now: https://github.com/pcapriotti/optparse-applicative/releases/tag/0.19.0

cc @nbacquey @Jimbo4350

2025-10-30 10:50 UTC, carbolymer commented
We're depending on cardano-addresses now, which depends on optparse-applicative. PR blocked on:
- https://github.com/IntersectMBO/cardano-addresses/issues/311

2025-11-04 12:07 UTC, Jimbo4350 requested changes
The change in the alignment is a decrease in readability IMO. Can we keep the previous alignment?

2025-11-04 12:07 UTC, Jimbo4350 commented on cardano-cli/app/cardano-cli.hs
> +renderAnyCmdError :: Text -> (a -> Doc ann) -> a -> Doc ann
Why not import from `Cardano.CLI.Type.Error.QueryCmdError`?

2025-11-04 12:07 UTC, Jimbo4350 commented on cardano-cli/test/cardano-cli-golden/files/golden/base_help.cli
> +Usage: cardano-cli (address | key | node | hash | query | legacy | byron |
Do we want this formatting change cc: @CarlosLopezDeLara

2025-11-04 12:07 UTC, Jimbo4350 commented on cardano-cli/test/cardano-cli-golden/files/golden/help.cli
> +Usage: cardano-cli address key-gen [--key-output-bech32 |
This seems like a decrease in readability.

2025-11-05 15:05 UTC, CarlosLopezDeLara commented on cardano-cli/test/cardano-cli-golden/files/golden/help.cli
> +Usage: cardano-cli address key-gen [--key-output-bech32 |
@Jimbo4350  @carbolymer 

I agree. 

I do like the compactness of things like: 
```
Usage: cardano-cli conway query protocol-parameters [--cardano-mode [--epoch-slots SLOTS]] (--mainnet | --testnet-magic NATURAL) --socket-path SOCKET_PATH [--output-json | --output-yaml] [--out-file FILEPATH] 
```

But in the other hand, the `build` command and others with more complex options are far too messy

<img width="1559" height="859" alt="Screenshot_20251105_090244" src="https://github.com/user-attachments/assets/6ffc7eb9-901c-437d-8141-da96d5fe6709" />

Let's not merge this one. It was a good idea trying to remove the burden of maintaining the fork, but we loose  readability.

2025-11-06 12:51 UTC, carbolymer commented
This PR results in decrease in readabilty, which seems to be not feasible to fix with the current version of `optparse-applicative-fork-0.19`.

2025-11-06 12:51 UTC, closed without merging