Gov action schema checking
IntersectMBO/cardano-cli pull request #995
Opened 2024-12-20 15:11 UTC by palas

# Changelog

```yaml
- description: |
    Added schema checking functionality for DRep registration, DRep update, and GovAction metadata, based on CIP-0100, CIP-0108, and CIP-0119. Update tests. Refactor test data for improved code clarity.
  type:
  - feature
  - refactoring
  - test
```

# Context

The objective is addressing this issue: https://github.com/IntersectMBO/cardano-cli/issues/906

This PR is based on [`cardano-api` PR #713](https://github.com/IntersectMBO/cardano-api/pull/713), which provides the required functionality, and this PR should not be merged until the `cardano-api` PR gets released and the source repo stanza is removed.

# How to trust this PR

I think, checking the changes to the tests here is key, and the main part. The actual functionality is in [`cardano-api` PR #713](https://github.com/IntersectMBO/cardano-api/pull/713) (I would check that one together with this). The latest commit should also be pure refactoring.

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

2024-12-21 18:33 UTC, gitmachtl commented
I just took a look at the testfiles and i noticed the one which has the authors signed with method "cip-0008".

The signature provided in this example is the COSE_SIGN1, ok. But the publicKey is not really the COSE_KEY, its only the public key. As CIP-0008 supports actually different methods, do we simply demand that the

COSE_Key map label '1' (kty) is '1' (OKP)
COSE_Key map label '3' (alg) is '-8' (EdDSA)
COSE_Key map label '-1' (crv) is '6' (Ed25519)

?

If so, is this written somewhere in the CIP-100 (and dependencies) ?

2025-02-13 13:58 UTC, Jimbo4350 requested changes
Nothing in the Haskell code indicates what the CIP is and links that to what is being checked/modified as a result of the CIP. We are setting ourselves up for failure when there are potentially dozens of cips and it's not *easily verifiable* as to what we have/have not implemented. Propose a solution to this and lets talk about it before you propagate it.

2025-02-13 13:58 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Actions.hs
> +  firstExceptT (GovernanceActionsHashCheckError checkType) $
I'm looking forward to wrapper code like this disappearing when we adopt `RIO`.

2025-02-13 14:27 UTC, gitmachtl commented
Not sure how useful it is putting time into this right now. There are a lot of ongoing discussion currently to change/edit/add stuff in der governance metadata CIPs. F.e. to make it more resistent against a replay attack for signed metadata. 

So not sure what checks are done in the cli about those metadata jsons, and if it makes sense to continue integrating this.

Most users are using 3rd party tools anyway for this.

2025-02-14 11:55 UTC, palas commented
> Nothing in the Haskell code indicates what the CIP is and links that to what is being checked/modified as a result of the CIP. We are setting ourselves up for failure when there are potentially dozens of cips and it's not easily verifiable as to what we have/have not implemented. Propose a solution to this and lets talk about it before you propagate it.

It would be ideal to have a way of validate the JSON schemas directly. I was trying that at the beginning, but JSON schema primitives are written quite informally and in natural language. And I couldn't find robust validators, from my view. It may be worth writing our own validator and give it some base implementations for native values. It may be less work than implementing validators for every CIP.

For getting a measure of completion, we could scan the CIPs for JSON schemas. But it is tricky to map them to actual artifacts. In fact, I am not sure that it is that well defined in the CIPs for now. We could try to request some structure from the CIPs that unequivocally identifies the artifacts they affect. But we would need some list that identifies all possible artifacts and gives them some unique identifier that can be mentioned in the CIP.

2025-02-14 11:55 UTC, palas commented
> Not sure how useful it is putting time into this right now. There are a lot of ongoing discussion currently to change/edit/add stuff in der governance metadata CIPs. F.e. to make it more resistent against a replay attack for signed metadata.
> 
> So not sure what checks are done in the cli about those metadata jsons, and if it makes sense to continue integrating this.
> 
> Most users are using 3rd party tools anyway for this.

Maybe it is not the best time for this then.

@Jordan, should we close this PR and park the task for now?

2025-02-14 11:56 UTC, palas commented
> Nothing in the Haskell code indicates what the CIP is and links that to what is being checked/modified as a result of the CIP. We are setting ourselves up for failure when there are potentially dozens of cips and it's not easily verifiable as to what we have/have not implemented. Propose a solution to this and lets talk about it before you propagate it.

Maybe it is not the best time for this, then.

@Jimbo4350, should we close this PR and park the task for now then?

2025-03-10 14:39 UTC, CarlosLopezDeLara commented
@palas yeah, park it!

2025-03-11 11:29 UTC, palas commented
Because the CIPs are not stable yet, we will be parking this feature for now, and get back to it in the future

2025-03-11 11:29 UTC, closed without merging